$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/ColourVariables.qvs?token=ANDyRRFDJaAjFTDRVklVTheLzRmM1x8Uks5X6Tx9wA%3D%3D);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/GenerateCalendar.qvs?token=ANDyRY1Ny5pE1RiXdT2vrErCWQ922UmIks5X6TyUwA%3D%3D);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/GenerateCommonCalendar.qvs?token=ANDyRYZ72PpFV25x7ti0qZEtZu_xFxgPks5X6TzlwA%3D%3D);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/IconsAndImages.qvs?token=ANDyRWrMkZSdiV2Ae_o8T_6fQODtDnm0ks5X6T0AwA%3D%3D);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/OutputTableAsHtml.qvs?token=ANDyRYeNVGRi2R73kJG01Y6cNocS38wqks5X6T0uwA%3D%3D);