$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/ColourVariables.qvs);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/GenerateCalendar.qvs);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/GenerateCommonCalendar.qvs);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/IconsAndImages.qvs);
$(include=https://raw.githubusercontent.com/GlutesDD/qlikview-scripts/master/OutputTableAsHtml.qvs);